package org.premsc.analyser.rules;

import io.github.treesitter.jtreesitter.Node;
import org.premsc.analyser.db.IndexModel;
import org.premsc.analyser.repository.ISource;

/**
 * Represents a warning generated by a rule during analysis.
 * @param rule the rule that generated the warning
 * @param source the source file where the warning occurred
 * @param line the line number in the source file where the warning occurred
 * @param startByte the starting byte position of the warning in the source file
 * @param endByte the ending byte position of the warning in the source file
 */
public record Warning(
        IRule rule,
        ISource source,
        int line,
        int startByte,
        int endByte
){

    /**
     * Constructs a Warning instance.
     * @param rule the rule that generated the warning
     * @param source the source file where the warning occurred
     * @param node the node in the syntax tree where the warning occurred
     */
    public Warning(IRule rule, ISource source, Node node) {
        this(rule, source, node.getStartPoint().row(), node.getStartByte(), node.getEndByte());
    }

    /**
     * Constructs a Warning instance.
     * @param rule the rule that generated the warning
     * @param source the source file where the warning occurred
     * @param index the index model containing the line and byte positions
     */
    public Warning(IRule rule, ISource source, IndexModel.Index index) {
        this(rule, source, index.line(), index.startByte(), index.endByte());
    }
}
